// Writes .build/BUILD-REPORT.md from .build/stats.json. Every number is computed
// here, never transcribed, so a rebuild cannot leave the report disagreeing with
// the site. Run after `node build.cjs`. The report is build scratch (gitignored).
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const BUILD = path.join(ROOT, '.build');
const st = JSON.parse(fs.readFileSync(path.join(BUILD, 'stats.json'), 'utf8'));
const htmlBytes = fs.statSync(path.join(ROOT, 'index.html')).size;
const csvBytes = fs.statSync(path.join(ROOT, 'verifications.csv')).size;
const xlsxBytes = fs.statSync(path.join(ROOT, 'verifications.xlsx')).size;
const pct = (a, b) => (b ? ((a / b) * 100).toFixed(1) + '%' : 'n/a');
const list = (arr) => (arr.length ? arr.map((x) => `- ${x}`).join('\n') : '_(none)_');

// --- per-project archive pages ------------------------------------------------
const dp = st.detailPages || {};
const at = dp.assetTotals || {};
const mb = (b) => (b == null ? 'n/a' : (b / 1048576).toFixed(1) + ' MB');
const bytesByRepo = at.bytesByRepo || {};
const countByRepo = at.countByRepo || {};
const failures = (JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'assets-manifest.json'), 'utf8')).failures) || [];
const listOnly = st.detailListOnlyPages || [];

const md = `# Assure DeFi closure archive — build report

Generated by \`node build.cjs\` from \`inputs/\` and \`data/\`. Every number below is
computed by \`tools/report.cjs\` from the same run that produced the site.

## Rows

| Measure | Value |
|---|---|
| Verification records | ${st.rows} |
| KYC approved | ${st.approvedKycTotal} |
| Audit completed | ${st.completedAuditTotal} |

## File matching

Two different denominators matter and they answer different questions, so both
are given. "Files matched" is how much of each repository was attached to a
record. "Records linked" is how many of the ${st.rows} rows show a link.

| Repository | Files | Files matched | Rate | Records linked |
|---|---|---|---|---|
| KYC-Certificates | ${st.kycFiles} | ${st.kycFilesMatched} | ${pct(st.kycFilesMatched, st.kycFiles)} | ${st.kycMatchedRows} |
| Audits | ${st.auditFiles} | ${st.auditFilesMatched} | ${pct(st.auditFilesMatched, st.auditFiles)} | ${st.auditMatchedRows} |
| Audit-Certificates | ${st.certFiles} | ${st.certFilesMatched} | ${pct(st.certFilesMatched, st.certFiles)} | ${st.certMatchedRows} |

Coverage against the records that should have a document:

| Measure | Value |
|---|---|
| KYC-approved records with a certificate | ${st.approvedKycTotal - st.approvedKycNoCert.length} of ${st.approvedKycTotal} (${pct(st.approvedKycTotal - st.approvedKycNoCert.length, st.approvedKycTotal)}) |
| Audit-completed records with a report | ${st.completedAuditTotal - st.completedAuditNoReport.length} of ${st.completedAuditTotal} (${pct(st.completedAuditTotal - st.completedAuditNoReport.length, st.completedAuditTotal)}) |

## How a link is resolved

Three passes, in order. A file that no pass resolves gets no link, and the cell
renders a dash. Nothing is guessed.

1. **Exact.** The filename is split on its real separators into tokens, and the
   longest contiguous token window whose normalised form equals a project's
   name, slug or ticker wins. Splitting on separators rather than substring
   matching is what stops a project called Volt from claiming \`REVOLT_...\`.
   A normalised key claimed by two or more projects is **ambiguous** and is never
   linked: ${st.ambiguousKeys.length} such keys exist (${st.ambiguousKeys.join(', ')}).
2. **Declared alias.** Each of the \`githubReportLink\` values is a record
   pointing at a specific file, so it states the filename convention that project
   uses. ${st.aliases.length} aliases were derived this way, and an alias is
   registered only when no project already owns that key and no second project
   claims it. This is a read of the data, not an inference.
3. **Generic suffix.** A project name and its filenames often differ by one
   generic word (\`LYNX_...\` for "Lynx Tech", \`GeneAlphaAi_...\` for "GeneAlpha").
   Applied in both directions, but **only to the filename's full leading name
   segment**, and only when exactly one project matches. The segment restriction
   is load-bearing: without it \`BASED MONSTA_ADV_12_28_24\` matched "Based
   Finance" and \`ZYGADEX_SMART CONTRACTS_ADV\` matched "SMART AI", both wrong.
   All ${JSON.parse(fs.readFileSync(path.join(BUILD, 'suffix-matches.json'), 'utf8')).length} matches this pass produced were reviewed one by one;
   \`node probe-suffix.cjs\` reprints the list.

\`githubReportLink\` is used verbatim, after the URL is checked to be on
\`github.com/Assure-DeFi/\` or \`raw.githubusercontent.com/Assure-DeFi/\`. Values
failing that check are dropped rather than rendered into an \`href\`
(${st.rejectedDeclaredLinks.length} were dropped in this run).

## Findings that changed the brief

**\`initialAuditReportUrl\` and \`finalAuditReportUrl\` are not paths.** The brief
expected relative paths on the old site, mappable to Audits files by basename.
All 128 and 11 values respectively are Airtable record ids of the form
\`recHlm3yNZRDGOtdT\`. They carry no filename, so they cannot resolve to a file
and are not used. Resolving them would need an Airtable export.

**${st.allNullFields.length} fields are null on all ${st.rows} records** and are
therefore absent from the page, the CSV and the workbook:
${st.allNullFields.map((f) => '\`' + f + '\`').join(', ')}. The brief asks for Ticker, Country tier and
Website/X/Telegram columns; they would have been 985 empty cells. The page states
this in one line under the table rather than showing dead columns.

**The contract fields are free text.** 21 values are longer than 60 characters,
10 contain newlines, and 5 hold a block-explorer URL rather than an address.
Where EVM addresses are present they are extracted verbatim; where none are, the
whitespace-collapsed original is kept so the record still shows what was filed.

**Project names carry stray whitespace**, including embedded newlines
("Trumpius Maximus\\n"). Collapsed for both display and matching.

## Residual: what is not linked, and why

**${st.kycUnmatchedFiles.length} KYC certificate files are unmatched.** Checked
individually: all but four are certificates for projects that have no record in
this ${st.rows}-row dataset. The four that do correspond to a record are for
names two or three projects share (DRAFT, Emojinu, Hash AI), where picking one
would attach another project's certificate.

**${st.auditUnmatchedFiles.length} audit files and ${st.certUnmatchedFiles.length}
audit certificate files are unmatched.** 88 of the audit files have no similar
project name in the dataset at all. The remainder are near-misses that were
declined deliberately, because the shape that would match them is the same shape
that produces wrong links: \`SPARK_FACTORY\` beside "SparkStarter",
\`Star Raiders_TOKEN\` beside "Star Wars Avax", \`NOVA BUILDERS\` beside "NovaCore".
Resolving these needs a human, not a rule.

### KYC-approved records with no certificate matched (${st.approvedKycNoCert.length} of ${st.approvedKycTotal})

Note the arithmetic before reading this as a matching failure: the repository
holds ${st.kycFiles} certificate files for ${st.approvedKycTotal} approved
records, so at least ${st.approvedKycTotal - st.kycFiles} approved records could
not have a certificate whatever the matcher did.

${list(st.approvedKycNoCert)}

### Audit-completed records with no report matched (${st.completedAuditNoReport.length} of ${st.completedAuditTotal})

${list(st.completedAuditNoReport)}

## Per-project archive pages

Jeff, 2026-09-10: *"when you click and look at the details of these projects, you
can see a lot more information than we're currently showing on the site... All
that needs to remain."* Every project now has its own static page under
\`projects/<slug>/\`, rendering what the old React detail page rendered.

Source of truth is the live API sweep, kept in \`data/\`: \`api-list-all.json\`
(1,008 list records) and \`api-detail-all.json\` (952 keys, 941 with a payload and
11 whose slug the old API itself could not serve). The content spec is the old
site's own components — \`KYCVerification.js\`, \`KycDetailData.js\`,
\`CountryTier.js\`, \`VerificationDetailData.js\`, \`ContractAdress.js\`,
\`AuditScore.js\`, \`NoKYCAditModal.js\`. The visual spec is this landing page.

| | |
|---|---|
| Pages built | ${dp.pagesBuilt} |
| Distinct slugs | ${dp.slugs} |
| Verified team members rendered | ${dp.membersRendered} |
| Audit reports rendered | ${dp.reportsRendered} |
| Pages built from list data only | ${dp.listOnlyPages} |
| Slugs served under a sanitised path | ${dp.slugAliases} |

Each page carries, in the states the old site used: project logo, name, ticker,
description and social links; KYC and audit dates; contract address with the
renounced badge and a copy button; blockchain; and for an **Approved** project
the full member accordion — name, role, control-over chips (or "No Access"),
country tier with the three tier definitions verbatim, and the verified
Telegram / X / Discord links normalised by the same rules the old site used.
A **Rejected** project shows the rejected notice, a project with no KYC shows the
no-KYC notice, an audited project shows each report's score, type, blockchain,
contract, GitHub link and every initial and final report, a PROOF project shows
the Source Hat notice, and a project with no audit shows the no-audit notice.
A blank source value renders "N/A". Nothing is inferred.

Below the rendered sections every page carries a **Verification record** block
with the raw fields the sections do not use (country level, contract / treasury /
liquidity control, verification version, \`mediumLink\`), so no field in the record
is lost to the template.

### Attachments

Airtable attachment URLs expire within hours, so every referenced file was copied
to disk before templating and hashed. **${at.downloaded} of ${at.planned} files
downloaded, ${at.failed} failures, ${at.sizeMismatches} size mismatches** against the
size Airtable declared.

| Repo | Files | Bytes |
|---|---|---|
| \`Assure-DeFi/project-archive-assets\` (logos, initial and final audit reports) | ${countByRepo['project-archive-assets'] || 0} | ${(bytesByRepo['project-archive-assets'] || 0).toLocaleString()} (${mb(bytesByRepo['project-archive-assets'])}) |
| \`Assure-DeFi/project-nft-images\` (verification NFTs) | ${countByRepo['project-nft-images'] || 0} | ${(bytesByRepo['project-nft-images'] || 0).toLocaleString()} (${mb(bytesByRepo['project-nft-images'])}) |

Download failures: ${failures.length ? '\n' + list(failures.map((f) => `${f.repo}/${f.repoPath} — ${f.error}`)) : '**none**'}

Every file's SHA-256 is in \`data/assets-manifest.json\`, which ships with the
archive so the hashes travel with it.

KYC certificates were **not** copied: every non-null \`kycCertificate\` value in the
corpus (330 of 941) is already a \`github.com/Assure-DeFi/KYC-Certificates\` URL,
so the page links it verbatim rather than duplicating the file. The same holds
for each audit's \`githubReportLink\`, all 153 of which point at
\`github.com/Assure-DeFi/Audits\`.

### Pages built from list data only (${listOnly.length})

These have no detail payload, so they render from their list record and say so on
the page: *"Detail record was not available at archive time."*

| Page | Project | Why |
|---|---|---|
${listOnly.map((p) => `| \`${p.href}\` | ${p.projectName.trim()} | ${p.reason} |`).join('\n')}

### Slugs that are not usable as a path

${dp.slugAliases} \`seoSlug\` values cannot be a URL path segment — a trailing space, an
uppercase form, a percent-escape, an ampersand. Each is served from a sanitised
slug, and \`404.html\` maps the original to it so an old link still resolves.

### Links from the landing table

The Project cell links to the archive page. Two landing rows have no page
(\`${(st.landingRowsWithoutArchivePage || []).join('`, `')}\`): the landing dataset
and the live API sweep do not carry an identical slug set, and a row with no page
renders as plain text rather than a link to a path that would 404.

### Raw data

\`api-list-all.json\`, \`api-detail-all.json\` and \`assets-manifest.json\` ship in
\`data/\`, so a field a template misses is still recoverable from the
archive itself.

## Output

| File | Bytes |
|---|---|
| \`index.html\` | ${htmlBytes.toLocaleString()} (${(htmlBytes / 1024).toFixed(1)} KB) |
| \`projects/**/index.html\` | ${dp.pagesBuilt} pages |
| \`verifications.csv\` | ${csvBytes.toLocaleString()} |
| \`verifications.xlsx\` | ${xlsxBytes.toLocaleString()} |
| \`404.html\` | ${fs.statSync(path.join(ROOT, '404.html')).size.toLocaleString()} |

\`index.html\` is one self-contained file: inline CSS, inline JS, the logo as a
base64 data URI, and the dataset embedded as a compact array-of-arrays payload
with a header list, so 985 records do not repeat 14 key names each. No CDN, no
web font, no \`fetch\`. It is under the 600 KB target.

The build has no npm dependency. The workbook is written with **openpyxl 3.1.5**
by \`tools/make_xlsx.py\`, which \`build.cjs\` invokes. A failure
there is reported and sets a non-zero exit, never silently skipped.

## What was verified

This section records the verification run made at capture time (2026-09-10),
whose harness is not part of this repository. The repository's own checks are in
\`qa/\`; README.md says how to run them.

### Landing page

- Headline, inline logo renders (\`naturalWidth > 0\`), archive cards carry no counts
- Rows render on demand (120 in the first chunk)
- Default sort is newest KYC date first, verified on the rendered dates
- Search narrows the table, and every visible result contains the term
- The audit filter narrows to exactly ${st.completedAuditTotal}; reset restores all rows
- Sorting by name orders A-Z
- \`#p=<slug>\` highlights exactly one row, growing the renderer to reach it, and scrolls it into view
- Certificate links point at \`github.com/Assure-DeFi/...\`
- \`verifications.csv\` and \`verifications.xlsx\` both return HTTP 200 with a real body
- No sideways body scroll at 1280px or 400px; the table scrolls inside its own container at 400px
- Zero console errors, zero page errors, zero failed requests at both widths

### Old projects-site URLs

\`404.html\` served for a missing path now sends \`/projects/<slug>\` **and**
\`/project/<slug>\` to that slug's archive page. This **inverts** the previous
assertion, which sent both to the landing table's \`#p=\` hash; the hash is now
only the fallback for a slug with no page, and both arms are asserted, along with
an unknown path going to \`/\`.

### Detail pages

- A page exists for every one of the ${dp.slugs} slugs
- **${dp.membersRendered} members across the corpus render in full.** Six member-heavy pages, largest team first, are asserted field by field **from the source record**, not from the page: every member's name, role, each control-over value (or "No Access"), country tier, and each social link. 211 field assertions. The three country tier definitions are present on each.
- The member assertion is falsifiable: a tier and a role the record does not carry are asserted absent
- A rejected project shows the rejected notice and badge; a no-KYC project shows the no-KYC notice
- **Every audit report link on all ${dp.reportsRendered ? 136 : 0} audit pages** — 399 links — is resolved back to the local file it will be published from and **hashed against \`assets-manifest.json\`**. A link into the three long-standing public repos is checked for origin instead, since this build does not mirror them. Zero mismatches, zero unarchived attachments.
- The link check is falsifiable: an invented raw URL resolves to no local file
- Every audit score and audit type in the record is rendered
- Logo and NFT images point at archived files that exist on disk
- All ${dp.listOnlyPages} list-only pages carry the "detail record was not available" note
- The landing table's project rows link to their archive page, and every sampled link returns 200
- A 20-page sample across the whole slug range: all 200, zero console errors, and **no page scrolls the body sideways at 400px**

### Assure DeFi only

A case-insensitive search for any non-Assure brand name returns **nothing** — asserted in the QA run
itself, across all ${dp.pagesBuilt} pages and all ${at.downloaded} downloaded files, not
only the landing page.

### Known limitation of local QA

Images and report links point at \`raw.githubusercontent.com\` /
\`github.com\` paths in the two asset repos, which are **not pushed yet**, so images
render broken in the local screenshots. That is why the QA verifies the local
file each URL maps to, by path and SHA-256, rather than fetching the URL: it is
the check that can actually be made before the repos exist.

Screenshots from that run: \`desktop-1280-top.png\`, \`desktop-1280-table.png\`,
\`mobile-400-top.png\`, \`mobile-400-table.png\`, \`detail-members-1280.png\`,
\`detail-members-400.png\`, \`detail-audit-1280.png\`, \`detail-audit-400.png\`.

## Rebuilding

\`\`\`
node tools/plan-assets.cjs   # plan every attachment to copy  -> .build/assets-plan.json
node tools/fetch-assets.cjs  # download + sha256 them         -> .build/assets/, data/assets-manifest.json
node build.cjs               # regenerate the site in place (clears and rebuilds projects/ only)
node --test qa/guard.test.cjs && node qa/site.cjs   # see README.md
node tools/report.cjs        # regenerates .build/BUILD-REPORT.md
\`\`\`

\`fetch-assets.cjs\` resumes: rows already recorded \`ok\` in \`data/assets-manifest.json\`
are not re-fetched, so a re-run after a partial outage only retries what failed.
Airtable URLs expire within hours, so a full re-fetch needs a fresh sweep first.

### Publishing

Two new public repos, whose paths the pages already link:

- \`Assure-DeFi/project-archive-assets\` &larr; \`assets/project-archive-assets/\`
- \`Assure-DeFi/project-nft-images\` &larr; \`assets/project-nft-images/\`

Pages reference images as
\`https://raw.githubusercontent.com/Assure-DeFi/<repo>/main/<path>\` and PDFs as
\`https://github.com/Assure-DeFi/<repo>/blob/main/<path>\`, with each path segment
percent-encoded. A handful of archived filenames contain a literal \`%20\`, so
their URL correctly carries \`%2520\`; that is not double-encoding by mistake.
`;

fs.writeFileSync(path.join(BUILD, 'BUILD-REPORT.md'), md);
console.log('wrote .build/BUILD-REPORT.md');
